# Generated by Django 2.0.5 on 2018-06-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20180619_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user',
        ),
    ]
