# Generated by Django 2.0.5 on 2018-06-15 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180616_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 0, 40, 18, 103620)),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 0, 40, 18, 104120)),
        ),
    ]
