# Generated by Django 2.0.5 on 2018-06-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20180616_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='caption',
        ),
    ]
