# Generated by Django 2.0.5 on 2018-06-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caption',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='abc', max_length=120),
            preserve_default=False,
        ),
    ]
